### ISSUE TITLE
Use Object.values() when available

### ISSUE THREAD

**Issue by zeke** [sindresorhus/object-values#8]
I just discovered that `Object.values()` is a thing: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values

It might be good to make this library use it if available, then fall back to the existing implementation.

**Comment by sindresorhus** [comment]
That would be bad. They don't have exactly the same behavior and that could cause inconsistencies between a `Object.values()` supporting and non-supporting environment.
