### ISSUE TITLE
Couldn't find package "@types/object-values" on the "npm" registry.

### ISSUE THREAD

**Issue by shinriyo** [sindresorhus/object-values#9]
I hope for TypeScript.

**Comment by SamVerschueren** [comment]
If they don't exist yet, you can easily publish them yourself in to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). For more info, see https://github.com/sindresorhus/ama/issues/439

**Comment by sindresorhus** [comment]
I now accept TypeScript definitions if anyone looking is interested in submitting it here.

See: https://github.com/sindresorhus/ama/issues/439#issuecomment-414212229

Please follow this guide: https://github.com/sindresorhus/typescript-definition-style-guide
